apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::062315287263:role/eksctl-Orchsky-cluster-nodegroup-NodeInstanceRole-1NPNM7VTBQ7NM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::062315287263:user/k8s-cluster-admin
      username: k8s-cluster-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::062315287263:user/prod-viewer
      username: prod-viewer
      groups: 
        - prod-viewer-role
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
