apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: efs-pvc-claim 
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-sc"
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: efs-sc
  resources:
    requests: 
      storage: 20Gi