kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: orchsky
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate