apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis-standby
spec:
  selector:
    matchLabels:
      app: redis 
      role: standby 
      tier: backend 
  replicas: 2
  template:
    metadata:
      labels:
        app: redis 
        role: standby 
        tier: backend 
    spec:
      containers:
        - name: standby
          image: gcr.io/google_samples/gb-redisslave:v1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports:
          - containerPort: 6379
