apiVersion: v1
kind: Service 
metadata:
  name: redis-standby
  labels:
    app: redis 
    role: standby 
    tier: backend 
spec:
  ports:
  - port: 6379
  selector:
    app: redis 
    role: standby 
    tier: backend 