kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-viewer-binding 
  namespace: production 
subjects:
- kind: User 
  name: prod-viewer
  apiGroup: ""
roleRef:
  apiGroup: ""
  kind: Role
  name: prod-viewer-role