kind: Role 
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: production 
  name: prod-viewer-role 
rules:
- apiGroups: ["", "extensions","apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]